#!/usr/bin/env python3

# Copyright © 2014-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import gzip
import sys
import tempfile

def main():
    ap = argparse.ArgumentParser(usage='%(prog)s < INPUT > OUTPUT')
    ap.parse_args()
    if sys.stdout.isatty():
        ap.error('stdout is a tty')
    s = sys.stdin.buffer.read()
    with tempfile.NamedTemporaryFile() as file:
        with gzip.GzipFile('', 'wb', compresslevel=0, fileobj=file, mtime=0) as gzfile:
            gzfile.write(s)
        file.seek(0)
        s = file.read()
    sys.stdout.buffer.write(s)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
